### ISSUE TITLE
What's Dictionary

### ISSUE THREAD

**Issue by KevinCotoCarrera** [nikoheikkila/photo-browser#16]
Can you please give me insights about what is the Dictionary you're using mainly inside your domain folder. Thanks beforehand

**Comment by nikoheikkila** [comment]
Hi! `Dictionary` is a simple [wrapper type](https://github.com/nikoheikkila/photo-browser/blob/ece0875e836146e7503bf702fd7dd50b272b6aa6/src/app.d.ts#L12) of arbitrary records.
